import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Home from "./home"
import Footer from "./footer";
import Doctors from "./doctor";
import Service from "@/pages/service"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home1() {
  return (
    <>
      <Head>
      <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
          <Home/>
          <h1 style={{
            fontSize: '60px',
            textAlign:' center',
            paddingTop: '50px'
          }}>Doctors</h1>
          <Doctors/>
          <h1 style={{
            fontSize: '60px',
            textAlign:' center',
            paddingTop: '50px',
            paddingBottom: '30px'
          }}>Service</h1>
          <Service/>
          <Footer/>
      </div>
         </>
  );
}
